[phases.setup]
nixPkgs = ["python312"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["DJANGO_SETTINGS_MODULE=taskboard.settings_prod python manage.py collectstatic --noinput"]

[start]
cmd = "python manage.py migrate && python manage.py initadmin && gunicorn taskboard.wsgi --log-file - --env DJANGO_SETTINGS_MODULE=taskboard.settings_prod"
